name: Dev Deployment and Merge to QA

on:
  push:
    branches:
      - dev  

jobs:
  deploy_to_dev_and_merge_to_qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Dev
        run: |
          chmod +x scripts/dev_deploy_script.sh  
          ./scripts/dev_deploy_script.sh  
        env:
          DEV_ENVIRONMENT_URL: https://adb-3943185736870612.12.azuredatabricks.net
          GITHUB_TOKEN: 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
          # Add other environment-specific secrets as needed

      - name: Merge to QA
        run: |
          git checkout origin/qa  
          git merge origin/dev  
          git push origin qa  
