name: Dev Deployment and Merge to QA

on:
  push:
    branches:
      - dev  # Trigger when changes are pushed to the dev branch

jobs:
  deploy_to_dev_and_merge_to_qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Dev
        run: |
          chmod +x dev_deploy_script.sh  # Ensure the script is executable
          .dev_deploy_script.sh  # Run the deployment script
        env:
          DEV_ENVIRONMENT_URL: https://adb-3943185736870612.12.azuredatabricks.net
          GITHUB_TOKEN: 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
          # Add other environment-specific secrets as needed

      - name: Merge to QA
        run: |
          git checkout qa  # Switch to the qa branch
          git merge origin/dev --no-edit  # Merge changes from dev without editing the merge commit message
          git push origin qa  # Push changes to the qa branch
